package com.briup.apps.ej.dao;

import com.briup.apps.ej.bean.BaseFile;
import com.briup.apps.ej.bean.BaseFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    long countByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int deleteByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int insert(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int insertSelective(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    List<BaseFile> selectByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    BaseFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseFile record, @Param("example") BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int updateByExample(@Param("record") BaseFile record, @Param("example") BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int updateByPrimaryKeySelective(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    int updateByPrimaryKey(BaseFile record);
}