package com.briup.apps.ej.bean;

public class BaseFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.id
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.fileName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.groupName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.uploadTime
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    private String uploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.fileSize
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    private Long filesize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.id
     *
     * @return the value of base_file.id
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.id
     *
     * @param id the value for base_file.id
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.fileName
     *
     * @return the value of base_file.fileName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.fileName
     *
     * @param filename the value for base_file.fileName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.groupName
     *
     * @return the value of base_file.groupName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.groupName
     *
     * @param groupname the value for base_file.groupName
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.uploadTime
     *
     * @return the value of base_file.uploadTime
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public String getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.uploadTime
     *
     * @param uploadtime the value for base_file.uploadTime
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public void setUploadtime(String uploadtime) {
        this.uploadtime = uploadtime == null ? null : uploadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.fileSize
     *
     * @return the value of base_file.fileSize
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public Long getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.fileSize
     *
     * @param filesize the value for base_file.fileSize
     *
     * @mbg.generated Sun Oct 27 19:05:52 CST 2019
     */
    public void setFilesize(Long filesize) {
        this.filesize = filesize;
    }
}