package com.briup.apps.ej.bean;

import io.swagger.annotations.ApiParam;

public class BaseUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.username
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    @ApiParam(value = "用户名",required = true)
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.realname
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    @ApiParam(value = "姓名",required = true)
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.password
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    @ApiParam(value = "密码",required = true)
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.enabled
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.type
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.telephone
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    @ApiParam(value = "手机号",required = true)
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.qq
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.wxid
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.register_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private Long registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.last_login_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private Long lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.last_login_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.register_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String registerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.gender
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.status
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.idcard_photo_positive
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String idcardPhotoPositive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.idcard_photo_negative
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String idcardPhotoNegative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.bank_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.bank_card_photo
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String bankCardPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.forbidden_reason
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String forbiddenReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.province
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.city
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.area
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.rank
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.comment
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id
     *
     * @return the value of base_user.id
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id
     *
     * @param id the value for base_user.id
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.username
     *
     * @return the value of base_user.username
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.username
     *
     * @param username the value for base_user.username
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.realname
     *
     * @return the value of base_user.realname
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.realname
     *
     * @param realname the value for base_user.realname
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.password
     *
     * @return the value of base_user.password
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.password
     *
     * @param password the value for base_user.password
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.enabled
     *
     * @return the value of base_user.enabled
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.enabled
     *
     * @param enabled the value for base_user.enabled
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.type
     *
     * @return the value of base_user.type
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.type
     *
     * @param type the value for base_user.type
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.telephone
     *
     * @return the value of base_user.telephone
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.telephone
     *
     * @param telephone the value for base_user.telephone
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.qq
     *
     * @return the value of base_user.qq
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.qq
     *
     * @param qq the value for base_user.qq
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.wxid
     *
     * @return the value of base_user.wxid
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.wxid
     *
     * @param wxid the value for base_user.wxid
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.register_time
     *
     * @return the value of base_user.register_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public Long getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.register_time
     *
     * @param registerTime the value for base_user.register_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.last_login_time
     *
     * @return the value of base_user.last_login_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.last_login_time
     *
     * @param lastLoginTime the value for base_user.last_login_time
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.last_login_ip
     *
     * @return the value of base_user.last_login_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.last_login_ip
     *
     * @param lastLoginIp the value for base_user.last_login_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.register_ip
     *
     * @return the value of base_user.register_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.register_ip
     *
     * @param registerIp the value for base_user.register_ip
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.gender
     *
     * @return the value of base_user.gender
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.gender
     *
     * @param gender the value for base_user.gender
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.status
     *
     * @return the value of base_user.status
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.status
     *
     * @param status the value for base_user.status
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id_card
     *
     * @return the value of base_user.id_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id_card
     *
     * @param idCard the value for base_user.id_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.idcard_photo_positive
     *
     * @return the value of base_user.idcard_photo_positive
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getIdcardPhotoPositive() {
        return idcardPhotoPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.idcard_photo_positive
     *
     * @param idcardPhotoPositive the value for base_user.idcard_photo_positive
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setIdcardPhotoPositive(String idcardPhotoPositive) {
        this.idcardPhotoPositive = idcardPhotoPositive == null ? null : idcardPhotoPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.idcard_photo_negative
     *
     * @return the value of base_user.idcard_photo_negative
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getIdcardPhotoNegative() {
        return idcardPhotoNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.idcard_photo_negative
     *
     * @param idcardPhotoNegative the value for base_user.idcard_photo_negative
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setIdcardPhotoNegative(String idcardPhotoNegative) {
        this.idcardPhotoNegative = idcardPhotoNegative == null ? null : idcardPhotoNegative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.bank_card
     *
     * @return the value of base_user.bank_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.bank_card
     *
     * @param bankCard the value for base_user.bank_card
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.bank_card_photo
     *
     * @return the value of base_user.bank_card_photo
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getBankCardPhoto() {
        return bankCardPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.bank_card_photo
     *
     * @param bankCardPhoto the value for base_user.bank_card_photo
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setBankCardPhoto(String bankCardPhoto) {
        this.bankCardPhoto = bankCardPhoto == null ? null : bankCardPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.forbidden_reason
     *
     * @return the value of base_user.forbidden_reason
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getForbiddenReason() {
        return forbiddenReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.forbidden_reason
     *
     * @param forbiddenReason the value for base_user.forbidden_reason
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setForbiddenReason(String forbiddenReason) {
        this.forbiddenReason = forbiddenReason == null ? null : forbiddenReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.province
     *
     * @return the value of base_user.province
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.province
     *
     * @param province the value for base_user.province
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.city
     *
     * @return the value of base_user.city
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.city
     *
     * @param city the value for base_user.city
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.area
     *
     * @return the value of base_user.area
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.area
     *
     * @param area the value for base_user.area
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.rank
     *
     * @return the value of base_user.rank
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.rank
     *
     * @param rank the value for base_user.rank
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.comment
     *
     * @return the value of base_user.comment
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.comment
     *
     * @param comment the value for base_user.comment
     *
     * @mbg.generated Mon Oct 28 12:57:00 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}