package com.briup.apps.ej.bean;

public class Waiter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.telephone
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.password
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.realname
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.gender
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.status
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.register_time
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private Long registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.score
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.order_quantity
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String orderQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.id_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.idcard_photo_positive
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String idcardPhotoPositive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.idcard_photo_negative
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String idcardPhotoNegative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.bank_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.bank_card_photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private String bankCardPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ej_waiter.address_id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    private Long addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.id
     *
     * @return the value of ej_waiter.id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.id
     *
     * @param id the value for ej_waiter.id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.telephone
     *
     * @return the value of ej_waiter.telephone
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.telephone
     *
     * @param telephone the value for ej_waiter.telephone
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.password
     *
     * @return the value of ej_waiter.password
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.password
     *
     * @param password the value for ej_waiter.password
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.realname
     *
     * @return the value of ej_waiter.realname
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.realname
     *
     * @param realname the value for ej_waiter.realname
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.gender
     *
     * @return the value of ej_waiter.gender
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.gender
     *
     * @param gender the value for ej_waiter.gender
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.status
     *
     * @return the value of ej_waiter.status
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.status
     *
     * @param status the value for ej_waiter.status
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.photo
     *
     * @return the value of ej_waiter.photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.photo
     *
     * @param photo the value for ej_waiter.photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.register_time
     *
     * @return the value of ej_waiter.register_time
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public Long getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.register_time
     *
     * @param registerTime the value for ej_waiter.register_time
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.score
     *
     * @return the value of ej_waiter.score
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.score
     *
     * @param score the value for ej_waiter.score
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.order_quantity
     *
     * @return the value of ej_waiter.order_quantity
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getOrderQuantity() {
        return orderQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.order_quantity
     *
     * @param orderQuantity the value for ej_waiter.order_quantity
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setOrderQuantity(String orderQuantity) {
        this.orderQuantity = orderQuantity == null ? null : orderQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.id_card
     *
     * @return the value of ej_waiter.id_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.id_card
     *
     * @param idCard the value for ej_waiter.id_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.idcard_photo_positive
     *
     * @return the value of ej_waiter.idcard_photo_positive
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getIdcardPhotoPositive() {
        return idcardPhotoPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.idcard_photo_positive
     *
     * @param idcardPhotoPositive the value for ej_waiter.idcard_photo_positive
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setIdcardPhotoPositive(String idcardPhotoPositive) {
        this.idcardPhotoPositive = idcardPhotoPositive == null ? null : idcardPhotoPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.idcard_photo_negative
     *
     * @return the value of ej_waiter.idcard_photo_negative
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getIdcardPhotoNegative() {
        return idcardPhotoNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.idcard_photo_negative
     *
     * @param idcardPhotoNegative the value for ej_waiter.idcard_photo_negative
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setIdcardPhotoNegative(String idcardPhotoNegative) {
        this.idcardPhotoNegative = idcardPhotoNegative == null ? null : idcardPhotoNegative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.bank_card
     *
     * @return the value of ej_waiter.bank_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.bank_card
     *
     * @param bankCard the value for ej_waiter.bank_card
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.bank_card_photo
     *
     * @return the value of ej_waiter.bank_card_photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public String getBankCardPhoto() {
        return bankCardPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.bank_card_photo
     *
     * @param bankCardPhoto the value for ej_waiter.bank_card_photo
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setBankCardPhoto(String bankCardPhoto) {
        this.bankCardPhoto = bankCardPhoto == null ? null : bankCardPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ej_waiter.address_id
     *
     * @return the value of ej_waiter.address_id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ej_waiter.address_id
     *
     * @param addressId the value for ej_waiter.address_id
     *
     * @mbg.generated Wed Oct 02 10:02:28 CST 2019
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
}